services:
  mysql:
    container_name: 'customerconnect-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=customerconnectdb'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'